# Generated by Django 6.1 on 2026-08-27 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beitrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('kategorie', models.CharField(blank=True, max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beitraege', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beitrag',
                'verbose_name_plural': 'Beiträge',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to=settings.AUTH_USER_MODEL)),
                ('beitrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='forum.beitrag')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
                'ordering': ['erstellt_am'],
            },
        ),
    ]
