# Generated by Django 6.1 on 2026-08-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kommentar',
            name='antwort_auf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antworten', to='forum.kommentar'),
        ),
        migrations.CreateModel(
            name='KommentarBewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('kommentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to='forum.kommentar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentar_bewertungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kommentar-Bewertung',
                'verbose_name_plural': 'Kommentar-Bewertungen',
                'unique_together': {('kommentar', 'user')},
            },
        ),
    ]
