# Generated by Django 6.1 on 2026-09-10 16:31

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAenderung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neue_email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_aenderungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail-Änderung',
                'verbose_name_plural': 'E-Mail-Änderungen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
