"""
Django settings for core project.
 
Generated by 'django-admin startproject' using Django 6.1.
 
For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
 
from datetime import timedelta
from pathlib import Path
import os
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^y#864n7e8n(nb7ymlv1s(1*st+-8b!ef7-p5+y=%f3yt!mvo('
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
 
ALLOWED_HOSTS = []
 
 
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
 
# NEU: nötig, damit der Browser die httpOnly-Auth-Cookies bei Cross-Origin-
# Requests vom React-Frontend (anderer Port) überhaupt mitschickt.
CORS_ALLOW_CREDENTIALS = True
 
# Application definition
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    # NEU: ohne diese beiden funktioniert djangorestframework-simplejwt nicht
    # (token_blacklist wird für das Logout/Blacklisting der Refresh-Tokens gebraucht)
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'termine',
    'forum',
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'core.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'core.wsgi.application'
 
 
# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'vv90'),
        'USER': os.environ.get('DB_USER', 'vv90'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'vv90dev'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}
 
# NEU: fehlte komplett. Ohne das nutzt Django weiterhin sein eingebautes
# User-Model statt unserem Custom User mit E-Mail-Login und Rollen.
# WICHTIG: muss gesetzt sein, BEVOR die erste Migration für 'accounts' läuft.
AUTH_USER_MODEL = 'accounts.User'
 
 
# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
# NEU: DRF-Konfiguration fehlte komplett. Damit greifen unsere Cookie-JWT-
# Authentifizierung und (als Fallback) die Standard-Header-Authentifizierung.
# DEFAULT_PERMISSION_CLASSES als Sicherheitsnetz: neue Views ohne explizite
# permission_classes sind dann automatisch NICHT öffentlich zugänglich.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.api.permissions.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}
 
# NEU: Einstellungen für die JWT-Tokens (Lebensdauer, Rotation).
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}
 
 
# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/
 
LANGUAGE_CODE = 'en-us'
 
TIME_ZONE = 'UTC'
 
USE_I18N = True
 
USE_TZ = True
 
 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
 
STATIC_URL = 'static/'
 
 
# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
 
# GEÄNDERT: 'MAILERS' ist kein gültiges Django-Setting und wurde bisher
# schlicht ignoriert. Django erwartet 'EMAIL_BACKEND'. Für lokale Entwicklung
# gibt die Konsolen-Backend die Mails im Terminal aus statt sie zu versenden.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@vv90.de'
 
# NEU: werden in accounts/api/utils.py für die Links in Einladungs- und
# Passwort-Reset-E-Mails gebraucht.
FRONTEND_URL = 'http://localhost:5173'
BACKEND_URL = 'http://localhost:8000'
 

