# Generated by Django 6.1 on 2026-08-26 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('typ', models.CharField(choices=[('spielplan', 'Spielplan'), ('mitgliederversammlung', 'Mitgliederversammlung'), ('turnier', 'Turnier'), ('training', 'Training'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=30)),
                ('ort', models.CharField(blank=True, max_length=200)),
                ('start', models.DateTimeField()),
                ('ende', models.DateTimeField(blank=True, null=True)),
                ('ist_wiederkehrend', models.BooleanField(default=False)),
                ('wiederholung_einheit', models.CharField(blank=True, choices=[('tage', 'Tage'), ('wochen', 'Wochen'), ('monate', 'Monate')], max_length=10)),
                ('wiederholung_abstand', models.PositiveIntegerField(blank=True, help_text='Zahl in Kombination mit der Einheit, z.B. Abstand=2 + Einheit=Wochen = alle 2 Wochen.', null=True)),
                ('wiederholung_bis', models.DateField(blank=True, help_text='Optional: Datum, ab dem die Wiederholung endet.', null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erstellte_termine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['start'],
            },
        ),
    ]
