# Generated by Django 6.1 on 2026-09-12 08:59

import dateien.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.FileField(upload_to=dateien.models.upload_pfad)),
                ('dateiname', models.CharField(max_length=255)),
                ('groesse', models.PositiveIntegerField(help_text='Dateigröße in Bytes')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('besitzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dateien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datei',
                'verbose_name_plural': 'Dateien',
                'ordering': ['-hochgeladen_am'],
            },
        ),
    ]
