# Generated by Django 6.1 on 2026-09-12 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateien', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datei',
            options={},
        ),
        migrations.CreateModel(
            name='Ordner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('besitzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordner', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unterordner', to='dateien.ordner')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='datei',
            name='ordner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dateien', to='dateien.ordner'),
        ),
    ]
